services:
  database:
    container_name: msqlbgd8
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookgarden
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: dusghchl3891!
      MYSQL_USER: bgdown
      MYSQL_PASSWORD: dusghchl3891!
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - msqlbgd-conf:/etc/mysql/conf.d
      - msqlbgd-data:/var/lib/mysql
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - book-garden_test_network

  application:
    image: book-garden-application
    container_name: book-garden
    restart: on-failure
    build:
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bookgarden?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "bgdown"
      SPRING_DATASOURCE_PASSWORD: "dusghchl3891!"
      PROFILE: dev
    depends_on:
      - database
    networks:
      - book-garden_test_network

volumes:
  msqlbgd-data:  # MySQL 데이터 파일 볼륨
  msqlbgd-conf:  # MySQL 설정 파일 볼륨

networks:
  book-garden_test_network:
    driver: bridge