spring:
  config:
    activate:
      on-profile: test_profile
  datasource-msqlbgd:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:bookgarden
    username: sa
    password:
  jpa:
    generate-ddl: 'true'
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        hibernate.default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console