spring:
  config:
    activate:
      on-profile: dev_profile
  datasource-msqlbgd:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: 'true'
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always